<script lang="ts">
	/**
	 * Generate TypeScript types, and write them into the project.
	 *
	 * Two steps rather than one, because the second is a file write into the
	 * user's repository. Generating shows exactly what would be written; writing
	 * is a separate, named action against a path the user can see and change.
	 *
	 * The path is resolved against the project root on the server and refused if
	 * it escapes — the value here is a suggestion, not a permission.
	 */
	import Icon from '$frontend/components/common/display/Icon.svelte';
	import Modal from '$frontend/components/common/overlay/Modal.svelte';
	import Button from '$frontend/components/common/display/Button.svelte';
	import InlineError from '$frontend/components/common/display/InlineError.svelte';
	import MonacoCodeEditor from '$frontend/components/common/editor/MonacoCodeEditor.svelte';
	import { dbAccountsStore } from '$frontend/stores/features/db-client-accounts.svelte';
	import { showSuccess } from '$frontend/stores/ui/notification.svelte';
	import { copyText } from '$frontend/utils/clipboard';

	interface Props {
		isOpen: boolean;
		connectionId: string;
		onClose: () => void;
	}

	let { isOpen = $bindable(), connectionId, onClose }: Props = $props();

	let schemas = $state('public');
	let path = $state('src/lib/database.types.ts');
	let types = $state('');
	let generating = $state(false);
	let writing = $state(false);
	let error = $state<string | null>(null);

	// Reset between openings: leaving the previous project's types on screen
	// while the dialog says a different project's name is the worst kind of
	// stale, because it looks correct.
	$effect(() => {
		if (isOpen) {
			types = '';
			error = null;
		}
	});

	async function generate(): Promise<void> {
		error = null;
		generating = true;
		try {
			const result = await dbAccountsStore.types(
				connectionId,
				schemas.split(',').map((entry) => entry.trim()).filter(Boolean)
			);
			types = result.types;
			if (result.suggestedPath && !path.trim()) path = result.suggestedPath;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Could not generate types';
		} finally {
			generating = false;
		}
	}

	async function write(): Promise<void> {
		error = null;
		writing = true;
		try {
			const result = await dbAccountsStore.writeTypes(connectionId, path.trim(), types);
			showSuccess('Types written', `${result.path} · ${result.bytes} B`);
			onClose();
		} catch (e) {
			error = e instanceof Error ? e.message : 'Could not write that file';
		} finally {
			writing = false;
		}
	}
</script>

<Modal bind:isOpen title="Generate TypeScript types" size="xl" onClose={onClose}>
	<div class="flex flex-col gap-3">
		<div class="flex items-end gap-2">
			<label class="flex flex-col gap-1 flex-1 min-w-0">
				<span class="text-xs text-slate-500 dark:text-slate-400">Schemas</span>
				<input
					type="text"
					bind:value={schemas}
					placeholder="public"
					class="px-2.5 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-md text-sm text-slate-900 dark:text-slate-100"
				/>
			</label>
			<Button size="sm" onclick={generate} disabled={generating} loading={generating}>
				Generate
			</Button>
		</div>

		{#if error}
			<InlineError message={error} onDismiss={() => (error = null)} />
		{/if}

		{#if types}
			<div class="h-[45vh] rounded-lg overflow-hidden border border-slate-200 dark:border-slate-800">
				<MonacoCodeEditor value={types} language="typescript" readonly height="100%" />
			</div>

			<div class="flex items-end gap-2">
				<label class="flex flex-col gap-1 flex-1 min-w-0">
					<span class="text-xs text-slate-500 dark:text-slate-400">
						Write to <span class="text-slate-400">(relative to the project root)</span>
					</span>
					<input
						type="text"
						bind:value={path}
						class="px-2.5 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-md text-sm text-slate-900 dark:text-slate-100"
					/>
				</label>
				<button
					type="button"
					class="flex items-center gap-1.5 px-2.5 h-9 rounded-md text-xs font-semibold text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 cursor-pointer"
					onclick={() => copyText(types)}
				>
					<Icon name="lucide:copy" class="w-3.5 h-3.5" />
					Copy
				</button>
				<Button size="sm" onclick={write} disabled={!path.trim() || writing} loading={writing}>
					Write file
				</Button>
			</div>
		{:else if !generating}
			<p class="text-xs text-slate-500 dark:text-slate-400">
				Types are generated by Supabase from the live schema. Nothing is written until you say so.
			</p>
		{/if}
	</div>
</Modal>
